services:
  - type: web
    name: my-app
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    redirects:
      - source: /*
        destination: /index.html
        status: 200
